### ISSUE TITLE
Arm64 for MacOS/Windows missing in compatability table

### ISSUE THREAD

**Issue by e12e** [WonderInventions/node-webrtc#1]
Looks like the compatability section in the readme needs an update. It is at least missing information on arm64 support for MacOS and Microsoft Windows.

It might be out of date overall.

https://github.com/WonderInventions/node-webrtc#supported-platforms

**Comment by hazelduvall** [comment]
@e12e In 3ecf646fc9c65cbe203408e8b0ccd0ed87abf28a I've updated the table to reflect availability of prebuilt binaries (https://www.npmjs.com/package/@roamhq/wrtc?activeTab=dependencies) and the version of Node I last tested with (18). Only MacOS has arm64 support at the moment.

**Comment by crisdosaygo** [comment]
I can confirm node 20 works. I didn't run tests, just integrated into the application and it worked!
