### ISSUE TITLE
Support for linux/arm64 

### ISSUE THREAD

**Issue by crisdosaygo** [WonderInventions/node-webrtc#3]
Hello @roamhq

I get this is probably not in your roadmap, so I'm sorry for bringing it up, but because I'm targeting a Docker image that can run on Apple Silicon using at least Node LTS, would it be a bad idea if for you to build for the linux/arm64 target for v18 and up?

In the meantime I'll try a cross-compile! 🥹

I totally get if you folks are simply too busy to reply or if anything else makes this impossible for you, and no worries at all, that's OK!--just thank you for making this wonderful updated library and for reading this far.

**Comment by hazelduvall** [comment]
Hi! There is currently no linux/arm64 support because I do not have an arm64 linux box to build on (haven't gotten around to setting up CI because some platforms require patches so it's just easier to do things locally), and didn't think the cross-compilation story on Linux is as smooth as it would be on MacOS.

So yeah it's just a story of "haven't tried it due to not enough time"! Let me know how it goes, I'd be happy to add that support if a cross-compile is as easy as changing a flag (as I recall it being on MacOS, after I debugged some things).

**Comment by crisdosaygo** [comment]
!! :joy: OK! My plan is basically to try to run the following Dockerfile on MacOS and see if I can build within that "Linux/Arm64" box:

```
# Use Debian 12 as the base image
FROM debian:12 as builder

# Set the environment variables as specified in the build instructions
ENV SKIP_DOWNLOAD=true
ENV TARGET_ARCH=arm64
ENV DEBUG=true

# Install the prerequisites
RUN apt-get update && \
    apt-get install -y git cmake build-essential ninja-build gcc-10 clang curl python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Install Node.js 20 (Stable)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# Clone the repository and switch to its directory
RUN git clone https://github.com/node-webrtc/node-webrtc.git
WORKDIR /node-webrtc

# Install the Node.js package and build the project
RUN npm install cmake-js -g
RUN npm install
RUN npm run build

# Run subsequent builds (not necessary, but kept for completeness)
RUN cmake --build build

# Run the tests
RUN npm test

# Keep the container open for inspection
CMD [ "bash" ]
```

via:

```
docker buildx create --use --name nodebuilder
docker buildx build --platform linux/arm64 -t node-webrtc-project .
docker run -it node-webrtc-project
```

**Comment by hazelduvall** [comment]
Tried this myself in a Debian arm64 VM. Failed during the build of LibWebRTC because it seems the build process assumed Linux meant x64 which was not the case, and things crashed when it tried to use a x64 `gn` binary.

This may change as the version of LibWebRTC we're targeting gets updated, but for now, it seems highly unlikely there'll be proper support for Linux arm64 soon unfortunately. Keeping the issue open as a tracker.

**Comment by crisdosaygo** [comment]
Thanks @duvallj that's great to know! So that I understand you, I think you're saying that we're hostage to an upstream dependency you folks use. Checking the page for that dependency ([here I assume](https://github.com/webrtc-sdk/libwebrtc)), it seems they do have arm64 for support.

So what I'm thinking now is may attempt to modify your library to patch in an arm version of libwebrtc. 

My naive hope is that this will not be as daunting as one may assume! 🤣

**Comment by hazelduvall** [comment]
So I had thought that the version of WebRTC we're targeting may have been too old for Linux arm64, but https://webrtc.googlesource.com/src/+/branch-heads/4606/g3doc/supported-platforms-and-compilers.md says otherwise. I'll give this another go later once I make my Linux arm64 setup a bit better, perhaps the CMakeLists.txt in this repository is wrong somehow.

**Comment by crisdosaygo** [comment]
Alright @duvallj sounds hopeful! If you have an Apple Silicon machine lying around maybe the Docker route is good too. I'll probably give a go sometime! 😊

**Comment by hazelduvall** [comment]
I do not have an Apple Silicon machine unfortunately, so I'm making do with my VMs on Windows :)

I successfully cross-compiled a Linux arm64 `wrtc.node` using https://developer.arm.com/downloads/-/gnu-a and quite a few modifications to my build scripts, but unfortunately it does not seem to pass all unit tests. Linux x64 also isn't passing all unit tests atm from that same revision too...

Ideally I'd like to fix these bugs before cutting a new version, but I've taken enough time as it is just getting the build. I've attached the release binary for Linux arm64 for anyone who wants to play around with it anyways, despite the potential bugginess. Unzip and place the resuling `wrtc.node` it in your `node_modules/wrtc/build` folder to use it. (debug binary is too big to attach)

[wrtc.zip](https://github.com/WonderInventions/node-webrtc/files/13045158/wrtc.zip)

**Comment by crisdosaygo** [comment]
Hey @duvallj I know it's late so totes understand if you've just lost it, but you didn't keep those modified build scripts did you? I'm currently trying to get Linux ARM to build (from Ubuntu 23.10) and Node v20. Kind of tricky. Here's what I've got so far:
```
#!/bin/bash

# Create an ARM (aarch64) Ubuntu 23.10 VM on Azure and then run
sudo apt update && sudo apt -y upgrade
source ~/.nvm/nvm.sh
command -v nvm || curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
sudo apt install -y cmake build-essential python-is-python3 pkg-config clang gn ninja-build
nvm install v20
nvm use v20
git clone https://github.com/dosyago/node-webrtc.git
cd node-webrtc
npm i
npm run build
sudo cp $(which gn) $HOME/node-webrtc/build/external/libwebrtc/download/src/buildtools/linux64/gn
cd build/external/libwebrtc/download/src/
build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
cd $HOME/node-webrtc
# running into issue with googletest
# so needed to 
# patch BUILD.gn
cp $HOME/BrowserBox/build-scripts/ubuntu-arm-patch/gtest-BUILD.gn ./build/external/libwebrtc/download/src/third_party/googletest/BUILD.gn
# also patch clang with correct exec 
cp $(which clang++) ./build/external/libwebrtc/download/src/third_party/llvm-build/Release+Asserts/bin/clang++
npm run build
```

But at this point the compile stops after output of a couple hundred error lines that look like then end in:

```
../../download/src/third_party/abseil-cpp/absl/types/optional.h:119:45: note: in instantiation of default argument for 'optional_data<unsigned int>' required here
class optional : private optional_internal::optional_data<T>,
                                            ^~~~~~~~~~~~~~~~
../../download/src/api/audio_codecs/audio_encoder.h:38:28: note: in instantiation of template class 'absl::optional<unsigned int>' requested here
  absl::optional<uint32_t> bitrate_action_counter;
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
ERR! OMG Process terminated: 1
/home/pro/node-webrtc/scripts/build-from-source.js:43
    throw new Error('cmake-js build failed for wrtc');
    ^

Error: cmake-js build failed for wrtc
    at main (/home/pro/node-webrtc/scripts/build-from-source.js:43:11)
    at Object.<anonymous> (/home/pro/node-webrtc/scripts/build-from-source.js:52:3)
```

ugh... 😂 

Idk...maybe I need to use: https://developer.arm.com/downloads/-/gnu-a ?? 🤔 

Just for a note: this is **not** super urgent. Due to difficulties in sending Chrome on ARM Linux anyway. :)

😂 haha it's all good if you can't get to it! No worries, just thanks for all the work you've done on it so far!!! :)

**Comment by hazelduvall** [comment]
Hi @o0101 ! Fortunately, I have kept these build scripts around! There could be some other modifications to libwebrtc source that I'm forgetting, but I *think* everything in the [linux-arm64-wip branch](https://github.com/WonderInventions/node-webrtc/tree/linux-arm64-wip) (that I literally just uploaded, thanks for having me rescue it from my hard drive!) should "just work" after you get the GCC ARM toolchain downloaded and pointed to by `toolchains/linux-arm64.toolchain`. Then, the command to build is just `TARGET_ARCH=arm64 npm run build`, no fiddling around with sysroots required :) (the ARM toolchain is it's own sysroot already iirc)

There are other issues with Node 20, though (https://github.com/WonderInventions/node-webrtc/issues/8), so I'm not sure how successful this will be... good luck! And if there are any other issues you encounter with the scripts I linked, please let me know so I can update them + add better instructions.

**Comment by crisdosaygo** [comment]
Awesome, man. It's always satisfying to get these builds actually working. Well done on your impressive work here, @duvallj! Very happy to see this this morning. Thank you so much! 🥇 :) 😹

**Comment by hazelduvall** [comment]
@o0101 I've published linux-arm64 binaries in the 0.7.2 version of `@roamhq/wrtc`, do you mind seeing if that works for you? Tentatively closing this issue, will re-open if it doesn't work.

**Comment by crisdosaygo** [comment]
Wow so cool! You did a lot of stuff! ❤️ Amazing @duvallj - I am not supporting ARM right now because of the difficulty getting Chrome to install on linux-arm systems (no official distribution, need snap, can't work in Docker easily, and my ARM effort was for the Docker image of BrowserBox). But I may return to this in future, and will likely use your bins then. 

So, ARM builds now? You merged in your branch? I can't find your branch and will wish to be guided by your work if I ever go back there! 🥺

I am so moved however that you did this! 🥺 You are truly awesome!!!! :) 💜 😄

**Comment by hazelduvall** [comment]
I did merge in the branch, yes! The main branch now supports the build and that's what I published the binary from.

The relevant commit is d4aceffb3820573640d913d8b871ee744a3be551 in case you want to take a look

**Comment by crisdosaygo** [comment]
Yay! 

I checked out that commit and -- so cool! It's really clean.

Wow, you are really an expert at this stuff. It's so cool to see! 😎 🏖️
