### ISSUE TITLE
Question regarding M94 and the license

### ISSUE THREAD

**Issue by ris-work** [WonderInventions/node-webrtc#9]
Hey, thank you for maintaining this project. However, I have a few questions.

The LICENSE document's copyright notices have not been updated with the recent changes. Is this project under the same license?

Is it necessarily M94 which is around 3 years old by now or does it work with later versions too?

Thank you for your time.

Regards,
Rishikeshan.

**Comment by hazelduvall** [comment]
Hi Rishikeshan! Thanks for your interest. I'll try to answer your questions:
1. Yes, the sources in this repository are still licensed under 2-clause BSD, so LICENSE.md is mostly correct.
2. THIRD_PARTY_LICENSES.md is likely out-of-date, additional licensing information for it can likely be found in [the M94 source](https://webrtc.googlesource.com/src/+/refs/branch-heads/4606). Seems like WebRTC itself is 3-clause BSD, not sure about the other projects it depends on.
3. This project does explicitly require M94 (see [CMakeLists.txt](https://github.com/WonderInventions/node-webrtc/blob/d567298049d8e6efd2a4a4d9ff0d6658476adb9f/CMakeLists.txt#L153)); updating to later versions is tricky given the continuous evolution of libwebrtc's API. I did the upgrade from M87 (last version supported by https://github.com/node-webrtc/node-webrtc) to M94 in a few steps (M87 -> M91 -> M92 -> M94). I was planning on doing an update to M98 and continuing beyond, but was moved to other priorities at work. Plus there are many other bugs with the library currently, and I wanted to fix those & get a solid base before continuing too.

Does this answer things for you?

**Comment by paweldomas** [comment]
Hi @duvallj 
Do you mind listing the most important remaining issues? We're trying to make a decision whether node-js wrapper for WebRTC is a viable option and might be able to help with some of the problems. The original repository is dead, but your fork gives some hope if it will be possible to bring it closer to the latest WebRTC version.

Also do you mind pushing your work in progress on the update to M98 to a branch? We might be able to help with that and open a PR.

**Comment by hazelduvall** [comment]
Hello @paweldomas ,

The most important remaining issues I'm aware of are https://github.com/WonderInventions/node-webrtc/issues/2 and https://github.com/WonderInventions/node-webrtc/issues/7 .

I have put up my M98 branch at https://github.com/WonderInventions/node-webrtc/tree/M98 (apologies but I don't quite recall how far I got on that) and a beginning of a fix for https://github.com/WonderInventions/node-webrtc/issues/7 at https://github.com/WonderInventions/node-webrtc/tree/remove-async-context-releaser (there is a TODO.md with the known issue).

As for being a viable option, I am not confident this library is ready for serious use without many more improvements. There are likely many other hidden issues that have not been caught from the minimal unit testing. Improvements on any front (more expansive testing, further stability, more recent WebRTC support) would be greatly appreciated.

**Comment by ris-work** [comment]
> Hi Rishikeshan! Thanks for your interest. I'll try to answer your questions:
> 
> 1. Yes, the sources in this repository are still licensed under 2-clause BSD, so LICENSE.md is mostly correct.
> 2. THIRD_PARTY_LICENSES.md is likely out-of-date, additional licensing information for it can likely be found in [the M94 source](https://webrtc.googlesource.com/src/+/refs/branch-heads/4606). Seems like WebRTC itself is 3-clause BSD, not sure about the other projects it depends on.
> 3. This project does explicitly require M94 (see [CMakeLists.txt](https://github.com/WonderInventions/node-webrtc/blob/d567298049d8e6efd2a4a4d9ff0d6658476adb9f/CMakeLists.txt#L153)); updating to later versions is tricky given the continuous evolution of libwebrtc's API. I did the upgrade from M87 (last version supported by https://github.com/node-webrtc/node-webrtc) to M94 in a few steps (M87 -> M91 -> M92 -> M94). I was planning on doing an update to M98 and continuing beyond, but was moved to other priorities at work. Plus there are many other bugs with the library currently, and I wanted to fix those & get a solid base before continuing too.
> 
> Does this answer things for you?

Thank you, it answers them.

**Comment by paweldomas** [comment]
@duvallj thank you for your answers that's very helpful! We'll try to take a look and see how it goes. Just a note that Linux is not a priority for us at this point (mostly Windows and Mac), so likely we won't be looking at #7 yet.
